# Generated by Django 5.0 on 2023-12-12 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offer',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
