# Generated by Django 5.0 on 2023-12-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to='assets/images/'),
        ),
    ]
