# Generated by Django 5.0 on 2023-12-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_cart_total_alter_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=40),
        ),
    ]
